### ISSUE TITLE
Support for multiple documents in a single CMake project

### ISSUE THREAD

**Issue by carlosjoserg** [wichtounet/CMakeLatex#1]
In the current implementation, this is not possible due to the fixed target names `pdf` and `auxclean` in lines 518-519. A possible workaourd that I'm using is to set those variables to:

``` cmake
SET(pdf_target      ${LATEX_TARGET})
SET(auxclean_target ${LATEX_TARGET}_clean)
```

And then you can add as many documents as wanted in one CMakeLists.txt, or nest projects, e.g. for several reports that share resources, etc.

Thus, after cmake config, one can type `make DOC1` and/or `make DOC2` to compile separately, or simply `make` to compile them all, since we always want the PDF in the end. The only problem I haven't solved is the `make clean` command, it only cleans the aux files of the latest added document.

I can provide a PR, but before, I wanted to raise the question to see whether you find it useful or not.

**Comment by wichtounet** [comment]
Hi,

Yes, you're absolutely right, it won't work with mutliple documents. I focused on a project that consists only on one latex document when putting together this CMake Utility. 

If you can provide a PR, that woul'd be great. 

For the clean issue, this comes from the fact that the list of files to be cleaned is computed in ADD_LATEX_TARGETS_INTERNAL and put in a single variable. It should perhaps be put in another place depending on the current target. 

Thanks

Baptiste
